AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS resources for the Catalog microservice

Parameters:
  StageName:
    Type: String
    Description: "API's stage name"
    Default: "dev"

  TableName:
    Type: String
    Description: "Table's name"
    Default: catalog

  UserPoolARN:
    Type: String
    Description: The ARN of the user pool that provides authentication
    Default: "dev"

Resources:
  ProductsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${TableName}_${StageName}
      PrimaryKey:
         Name: id
         Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5

  CatalogApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors: "'*'"

  CatalogApiController:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/apiController.handler
      MemorySize: 1024
      Timeout: 60
      Runtime: nodejs8.10
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          TABLE_NAME: !Ref ProductsTable
      Policies: 
        - AmazonDynamoDBFullAccess
        - Statement:
            - Effect: Allow
              Action: cloudsearch:search
              Resource: "*"
      Events:
        ProxyGet:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogApi
            Path: /{proxy+}
            Method: GET
        ProxyOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogApi
            Path: /{proxy+}
            Method: OPTIONS

Outputs:
  ApiUrl:
    Description: Gateway API URL
    Value: !Sub https://${CatalogApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/
