AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS resources for the Catalog microservice

Parameters:
  StageName:
    Type: String
    Description: "API's stage name"
    Default: "dev"

  TableName:
    Type: String
    Description: "Table's name"
    Default: catalog

  UserPoolARN:
    Type: String
    Description: The ARN of the user pool that provides authentication
    Default: "dev"

Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TableName}_${StageName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  CatalogApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors: "'*'"

  CatalogApiController:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/apiController.handler
      MemorySize: 1024
      Timeout: 60
      Runtime: nodejs8.10
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          TABLE_NAME: !Ref ProductsTable
          SEARCH_HOSTNAME_SECRET: "CloudSearch/Hostname"
      Policies: 
        - AmazonDynamoDBFullAccess
        - Statement:
            - Effect: Allow
              Action: cloudsearch:search
              Resource: !Sub arn:${AWS::Partition}:cloudsearch:${AWS::Region}:${AWS::AccountId}:domain/catalog-search 
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:CloudSearch/Hostname-*
      Events:
        ProxyGet:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogApi
            Path: /{proxy+}
            Method: GET
        ProxyOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogApi
            Path: /{proxy+}
            Method: OPTIONS

  DBStreamController:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/dbStreamController.handler
      MemorySize: 1024
      Timeout: 60
      Runtime: nodejs8.10
      Events:
        DBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt ProductsTable.StreamArn
            StartingPosition: LATEST
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:ListStreams
            Resource: !GetAtt ProductsTable.Arn
        - Statement:
          - Effect: Allow
            Action: cloudsearch:document
            Resouce: !Sub arn:${AWS::Partition}:cloudsearch:${AWS::Region}:${AWS::AccountId}:domain/catalog-search

Outputs:
  ApiUrl:
    Description: Gateway API URL
    Value: !Sub https://${CatalogApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/
